// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHyGasE5XdnWpBvBeCXYzx9IBjEt8DJQs',
    appId: '1:170888753402:web:563d897055cad2b84b5943',
    messagingSenderId: '170888753402',
    projectId: 'logistics-0',
    authDomain: 'logistics-0.firebaseapp.com',
    storageBucket: 'logistics-0.firebasestorage.app',
    measurementId: 'G-4F2G0WNSF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl4kXt6cxDM9wE9rZ7bfhpbhLtbt8meJU',
    appId: '1:170888753402:android:62e66e9bcd23eace4b5943',
    messagingSenderId: '170888753402',
    projectId: 'logistics-0',
    storageBucket: 'logistics-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeezkvWOlC-AcxszzZDl4d78_g7KAPjh0',
    appId: '1:170888753402:ios:23ddcff6e970d8fa4b5943',
    messagingSenderId: '170888753402',
    projectId: 'logistics-0',
    storageBucket: 'logistics-0.firebasestorage.app',
    iosBundleId: 'com.example.logestics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeezkvWOlC-AcxszzZDl4d78_g7KAPjh0',
    appId: '1:170888753402:ios:23ddcff6e970d8fa4b5943',
    messagingSenderId: '170888753402',
    projectId: 'logistics-0',
    storageBucket: 'logistics-0.firebasestorage.app',
    iosBundleId: 'com.example.logestics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHyGasE5XdnWpBvBeCXYzx9IBjEt8DJQs',
    appId: '1:170888753402:web:f8b96a861ddd51d34b5943',
    messagingSenderId: '170888753402',
    projectId: 'logistics-0',
    authDomain: 'logistics-0.firebaseapp.com',
    storageBucket: 'logistics-0.firebasestorage.app',
    measurementId: 'G-5NEQ3FQSFJ',
  );

}